
server:
  error:
    include-message: always
spring:
  ldap:
    embedded:
      port: 8389
      ldif: classpath:ldap-data.ldif
      base-dn: dc=springframework,dc=org
  datasource:
    url: 'jdbc:mysql://localhost:3306/schedule'
    username: root
    password: mrbui123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
welcome:
  message: Welcome to the server!
